from PIL import Image
from sys import argv

def main():
	if len(argv) == 1:
		print("Usage: py img2h.py <image>")
		return
	img = Image.open(argv[1])
	w, h = img.size
	img_name = argv[1].split('.')[0]
	f = open(img_name + ".h", 'w')
	f.write('// auto generated by img2h\n// size: %dx%d\n\n#include "../../include/fblib.h"\n\nconst unsigned char %s_data[] = { ' % (w, h, img_name))
	first = True
	for y in range(h):
		for x in range(w):
			px = img.getpixel((x, y))
			if first:
				f.write("0x%x, 0x%x, 0x%x, 0x%x" % (px[0], px[1], px[2], px[3]))
				first = False
			else:
				f.write(", 0x%x, 0x%x, 0x%x, 0x%x" % (px[0], px[1], px[2], px[3]))
	f.write(" };\n")
	f.write("const struct image %s = { %d , %d, %s_data };" % (img_name, w, h, img_name))
	f.close()
	
main()